apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  title: DE Workflow Template
  name: de-workflow-template
  annotations:
    github.com/project-slug: thinkingmachines/de-workflow-template
  tags:
    - internal
    - data-warehouse
spec:
  type: internal
  lifecycle: development
  owner: dpd-des
  parameters:
    - title: Create a new de-workflow-template repository
      required:
        - repoUrl
        - description
      properties:
        repoUrl:
          title: Repository Name
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
            allowedOwners:
              - thinkingmachines
        description:
          title: Repository Description
          type: string
          description: Describe repository in 1 to 2 sentences
          ui:autofocus: true
  steps:
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
      input:
        url: .
        values:
          owner: thinkingmachines
  
    - id: publish
      name: Publish
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: ${{ parameters.description }}
        repoUrl: ${{ parameters.repoUrl }}
        gitAuthorName: ${{ user.entity.metadata.name }}
        gitAuthorEmail: ${{ user.entity.metadata.annotations['google.com/email'] }}
        collaborators:
        - user: ${{ user.entity.metadata.name }}
          access: admin
  
    - id: register
      name: Register
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: '/catalog-info.yaml'
